#!/bin/bash

function instruct {
    cmd="qdbus org.kde.yakuake $1"
    eval $cmd &> /dev/null
    sleep 0.5
}

instruct "/yakuake/sessions org.kde.yakuake.addSession"
instruct "/yakuake/sessions org.kde.yakuake.addSession"

instruct "/yakuake/tabs org.kde.yakuake.setTabTitle 0 Home"
instruct "/yakuake/tabs org.kde.yakuake.setTabTitle 1 htop"

instruct "/Sessions/1 org.kde.konsole.Session.sendText 'cd'"
instruct "/Sessions/2 org.kde.konsole.Session.sendText 'htop'"

instruct "/Sessions/1 org.kde.konsole.Session.sendText \$'\n'"
instruct "/Sessions/2 org.kde.konsole.Session.sendText \$'\n'"
